function eventFlow(e) {
  console.log(`Hello, "${this}" is greating you, this click was generated by "${e.target.className}"`) //~this is document

  //e.stopPropagation() //^ stop propagation is not necessary because the event was assigned to the father element (document)
}

//* En lugar de haber tenido 4 listeners, solamente tengo la asignación de un "listener" al evento click del nodo principal "document". Con esta técnica a parte de mejorar el rendimiento solamente estamos teniendo una sola asignación al evento "click". A través del condicional "if" evaluamos los eventos:
document.addEventListener('click', e => {
  console.log(e.target) //^ <- target of any document element

  if(e.target.matches('.event-flow div')){
    eventFlow(e)
  }

  if(e.target.matches('.event-flow a')){
    alert('HELLO SECRET WORLD!')
    e.preventDefault() //^ <- prevents the action of the tag
  }
})